version: '2'
services:
  energypoint:
    image: membership/energypoint:latest
    build: .
    container_name: dkt_mb_enp
    environment:
      - PGHOST=rtdkv1pgs01.c0x6zghvypsc.rds.cn-north-1.amazonaws.com.cn
      - PGUSER=membership
      - PGDATABASE=db_energy_point
      - PGPASSWORD=mypassword
      - PGPORT=5432